emit:
  - "@typespec/openapi3"
  - "@azure-tools/typespec-ts"
  - "@typespec/http-server-js"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/schema"
    openapi-versions:
      - 3.1.0
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/clients/js"
  "@typespec/http-server-js":
    emitter-output-dir: "{output-dir}/server"
